controller:
  ingressClass: 'pvindia-ingress'
  image:
    allowPrivilegeEscalation: false
  ingressClassResource:
    name: 'pvindia-ingress'
    controllerValue: "k8s.io/pvindia-ingress"
    enabled: true
  replicaCount: 1