
{{- if and .Values.clusterissuer.enabled (eq .Values.controller.ingressClassResource.name "nginx-dev-ingress") }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
# kind: Issuer
metadata:
  name: letsencrypt-public-ingress-dev

spec:
  acme:
   # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
       # Email address used for ACME registration
    email: software.vcontrol@iplon.co.in
       # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-public-ingress-dev
       # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
             class:  public-ingress-dev
{{- end }}